# Generated by Django 5.1.5 on 2026-04-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='emotion_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='emotion_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='emotion_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='emotion_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='music_query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='recommendation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='sub_emotion_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='sub_emotion_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
