# Generated by Django 5.1.5 on 2026-04-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diary_emotion_label_diary_emotion_raw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='music_query',
        ),
        migrations.AddField(
            model_name='diary',
            name='recommendation_song',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
