# Generated by Django 5.1.5 on 2026-04-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_remove_diary_music_query_diary_recommendation_song_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={},
        ),
        migrations.RemoveField(
            model_name='diary',
            name='emotion_label',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='emotion_raw',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='emotion_score',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='emotion_summary',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='sub_emotion_label',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='sub_emotion_score',
        ),
        migrations.AlterField(
            model_name='diary',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
